# La configuration contient les éléments suivants:
# PATH: On assure que le PATH est complet
# PATH_SCRIPT: Dossier contenant tous les scripts
# URL_API: Url de l'api rest recevant les données
# IFACE: Interface d'écoute des paquets
# PATH_DUMP: Dossier de sauvegarde des dumps
# PATH_SESSION: Dossier contenant la session
# PATH_DUMP_CURRENT: Dossier de sauvegarde de l'écoute en cours
# PATH_DUMP_TMP: Dossier de sauvegarde de fichiers temporaires
# PATH_DUMP_WAITING: Dossier de sauvegarde de fichiers en attente d'être envoyé sur serveur
# FILE_CURRENT: Fichier de lecture courant
# SEPARATOR: Séparateur de champs
# FILE_USER_ID: Fichier contenant l'id de l'utilisateur
# FILE_USER_KEY: Fichier contenant la clé de l'utilisateur
# SCAPY_FILTER: Filtre utilisé pour ne pas récupérer tous les paquets et optimisé l'écoute
# LISTEN_TIMEOUT: Temps d'écoute des paquets avant d'arrêter l'écoute et la relancer

# Configuration pour le programme principal
main:
    PATH: /sbin:/usr/sbin:$PATH
	PATH_SCRIPT: /home/realitix/git/tracker-hardware/lib
	URL_API: http://localhost/api/captures
	IFACE: wlan0
	PATH_DUMP: /home/realitix/git/tracker-hardware/dump
	PATH_SESSION: /home/realitix/git/tracker-hardware/session
	PATH_DUMP_CURRENT: /home/realitix/git/tracker-hardware/dump/current
	PATH_DUMP_TMP: /home/realitix/git/tracker-hardware/dump/tmp
	PATH_DUMP_WAITING: /home/realitix/git/tracker-hardware/dump/waiting
	FILE_CURRENT: /home/realitix/git/tracker-hardware/dump/current/current.txt
	SEPARATOR: ||
	FILE_USER_ID: /home/realitix/git/tracker-hardware/session/userId
	FILE_USER_KEY: /home/realitix/git/tracker-hardware/session/userKey
	FILE_PLACE_ID: /home/realitix/git/tracker-hardware/session/placeId
	SCAPY_FILTER: type mgt and (subtype probe-req or subtype assoc-req or subtype reassoc-req)
	LISTEN_TIMEOUT: 60

# Configuration pour le programme de mise à jour
